# HomeWork

## Importing Libraries and Downloading Dataset

In [9]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-30 13:24:05--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv


Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
^C


In [ ]:
!uv add numpy pandas matplotlib seaborn

Resolved 47 packages in 2.24s                                        
⠸ Preparing packages... (0/11)                                                  ⠋ Preparing packages... (0/0)                                                   
⠸ Preparing packages... (0/11)---     0 B/497.29 KiB                    
tzdata     ------------------------------     0 B/339.69 KiB
⠸ Preparing packages... (0/11)---     0 B/497.29 KiB                    
pyparsing  ------------------------------     0 B/111.22 KiB
tzdata     ------------------------------     0 B/339.69 KiB
⠸ Preparing packages... (0/11)---     0 B/497.29 KiB                    
pyparsing  ------------------------------     0 B/111.22 KiB
tzdata     ------------------------------ 14.88 KiB/339.69 KiB
⠼ Preparing packages... (0/11)---     0 B/497.29 KiB                    
pyparsing  ------------------------------     0 B/111.22 KiB
tzdata     ------------------------------ 14.88 KiB/339.69 KiB
⠼ Preparing packages... (0/11)---     0 B/497.

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from numpy.linalg import inv

In [20]:
data = pd.read_csv("car_fuel_efficiency.csv")
data.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [21]:
pd.__version__

'2.3.3'

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [23]:
data['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [24]:
data.isnull().any().sum()

np.int64(4)

In [25]:
cleandata = data.dropna()
cleandata["origin"] = cleandata['origin'].apply(lambda x: x.lower())
cleandata.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7333 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  7333 non-null   int64  
 1   num_cylinders        7333 non-null   float64
 2   horsepower           7333 non-null   float64
 3   vehicle_weight       7333 non-null   float64
 4   acceleration         7333 non-null   float64
 5   model_year           7333 non-null   int64  
 6   origin               7333 non-null   object 
 7   fuel_type            7333 non-null   object 
 8   drivetrain           7333 non-null   object 
 9   num_doors            7333 non-null   float64
 10  fuel_efficiency_mpg  7333 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 687.5+ KB


/tmp/ipykernel_94099/132027337.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleandata["origin"] = cleandata['origin'].apply(lambda x: x.lower())


In [26]:
asia_fuel_eff = cleandata[cleandata["origin"] == "asia"]
asia_fuel_eff['fuel_efficiency_mpg'].max()

np.float64(23.03367321593866)

In [28]:
init_median = data["horsepower"].median()
init_median

np.float64(149.0)

In [31]:
occure = data['horsepower'].value_counts()
occure

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [34]:
final_median = data["horsepower"].fillna(152).median()
final_median

np.float64(152.0)

In [35]:
init_median > final_median

np.False_

In [46]:
# asia_cars = cleandata[cleandata["origin"] == "asia"]
# two_col = asia_cars[['vehicle_weight', 'model_year']]
X = cleandata.loc[cleandata.origin == "asia", ["vehicle_weight", "model_year"]].iloc[:7]
X
x = X.to_numpy()
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2844.22753389, 2014.        ],
       [2957.68110989, 2012.        ],
       [2544.51680177, 2016.        ]])

In [44]:
xt = X.T.to_numpy()
xt

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2844.22753389, 2957.68110989, 2544.51680177],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2014.        , 2012.        , 2016.        ]])

In [51]:
xtx = np.matmul(xt,x)
print(xtx, xtx.shape)

[[56245602.84911267 39554937.0049519 ]
 [39554937.0049519  28345122.        ]] (2, 2)


In [49]:
y = np.float64([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100., 1300.,  800.,  900., 1000., 1100., 1200.])

In [56]:
i_v = inv(xtx)@xt
i_v

array([[-9.45558029e-05, -2.00811239e-05,  7.46409448e-04,
        -5.48370658e-04,  3.22047268e-05,  1.43163382e-04,
        -2.56541595e-04],
       [ 2.03073701e-04,  9.89343983e-05, -9.70790625e-04,
         8.36185034e-04,  2.61118671e-05, -1.28798830e-04,
         4.29120984e-04]])

In [54]:
w = (inv(xtx)@xt)@y
w

array([-0.14468835,  0.72730815])

In [55]:
sum(w)

np.float64(0.5826198096600923)